.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. credits_qt test_credits_qt
clean: FORCE
	$(MAKE) -C .. credits_qt_clean test_credits_qt_clean
check: FORCE
	$(MAKE) -C .. test_credits_qt_check
credits-qt credits-qt.exe: FORCE
	 $(MAKE) -C .. credits_qt
